#%RAML 1.0 DataType
type: object
properties:
	
    Id:
        displayName: Identifier
        description: Primary Key
        type: string
        required: true
	
    Description:
        displayName: Description
        description: Description of the region
        type: string
        required: true
	
    GeographicRegionScopeId:
        displayName: Geographic Region Scope
        description: How big part of the world does the geography cover e.g.,
        type: string
        required: true
	
    LandAreaSizeUOMId:
        displayName: Land Area Size UOM
        description: Physical size Unit of Measure e.g. square miles
        type: string
        required: false
	
    TimezoneId:
        displayName: Timezone
        description: A range of longitudes where a common standard time is used.
        type: string
        required: false
	
    LastUpdatedDt:
        displayName: Last Updated Date Time
        description: Date and time when record was last updated
        type: datetime-only
        required: true
	
    GeoLat:
        displayName: Geo Latitude
        description: Geographic Latitude in Decimal Degrees (WGS1984)
        type: number
        required: false
	
    GeoLgtd:
        displayName: Geo Longitude
        description: Geographic Longitude in Decimal Degrees (WGS1984)
        type: number
        required: false
	
    GeoAccuracyNbr:
        displayName: Geo Accuracy
        description: How accurte the geographical location is
        type: number
        required: false
	
    PopulationCnt:
        displayName: Population Count
        description: How many people exist in the geographical region
        type: number
        required: false
	
    LandAreaSizeNbr:
        displayName: Land Area Size
        description: Physical size of the surface of the geographical region
        type: number
        required: false
	
    ImplementerType:
        displayName: Implementer Type
        description: Entity Interfaces may have implementers other than the default implementation. Provides a way to specify which implementation, for example when an Insert operation should only be performed on one of several substrates that implement the EI.
        type: string
        required: false
	
    ExternalRecordId:
        displayName: External Record Id
        description: Corresponding record Id from external data source system
        type: string
        required: false
	
    ExternalSystemName:
        displayName: External System Name
        description: Name of the system where the External Record Id exists
        type: string
        required: false
	
    CreatedDate:
        displayName: Created Date
        description: Date and time when this record was created
        type: datetime-only
        required: true
	
    CreatedByUserId:
        displayName: Created By User Id 
        description: User who created the record
        type: string
        required: true
	
    LastModifiedDate:
        displayName: Last Modified Date
        description: Date and time when a user last modified this record
        type: datetime-only
        required: true
	
    LastModifiedById:
        displayName: Last Modified By Id
        description: User who most recently changed the record
        type: string
        required: true
	
    SystemModstamp:
        displayName: System Modified Stamp
        description: Date and time when this record was last modified by a user or by an automated process
        type: datetime-only
        required: true
